name: CI

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: zi-gae/frontend-bot@v1.10.0
        with:
          plane-text: HELLO  WROLD  TEST \n TEST `REACT`
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          channel-id: ${{ secrets.CHNNAL_ID }}
